ALTER TABLE hotels
  ADD COLUMN IF NOT EXISTS slug         TEXT,
  ADD COLUMN IF NOT EXISTS region       TEXT,
  ADD COLUMN IF NOT EXISTS city_slug    TEXT,
  ADD COLUMN IF NOT EXISTS email        TEXT,
  ADD COLUMN IF NOT EXISTS michelin_url TEXT,
  ADD COLUMN IF NOT EXISTS keys_level   SMALLINT,
  ADD COLUMN IF NOT EXISTS lodging_type TEXT,
  ADD COLUMN IF NOT EXISTS rooms_count  INTEGER,
  ADD COLUMN IF NOT EXISTS amenities    JSONB,
  ADD COLUMN IF NOT EXISTS is_plus      BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS neighborhood TEXT;
